# Generated by Django 6.0.3 on 2026-03-18 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicostatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatus',
            options={'verbose_name_plural': 'Históricos de Status'},
        ),
        migrations.RemoveField(
            model_name='historicostatus',
            name='usuario_responsavel',
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_anterior',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_novo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa_geral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
