# Generated by Django 6.0.3 on 2026-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicostatus_usuario_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='link_entrevista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='score_comportamental',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sophia_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
