# Generated by Django 6.0.3 on 2026-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_candidato_link_entrevista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='descricao',
            new_name='descricao_sumaria',
        ),
        migrations.AddField(
            model_name='vaga',
            name='arquivo_vaga',
            field=models.FileField(blank=True, null=True, upload_to='vagas/'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='diferenciais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='requisitos_obrigatorios',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='responsabilidades',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(default='aberto', max_length=20),
        ),
    ]
