# Generated by Django 6.0.3 on 2026-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_descricao_vaga_descricao_sumaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura Real'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
    ]
