# Generated by Django 6.0.3 on 2026-04-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vaga_data_abertura_vaga_data_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_vaga', to='core.vaga')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
